config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :productlines
  resources :payments
  resources :orders
  resources :orderdetails
  resources :offices
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root to: 'products#index'
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
end

app/controllers/orderdetails_controller.rb
class OrderdetailsController < ApplicationController
  before_action :set_orderdetail, only: [:show, :edit, :update, :destroy]

  # GET /orderdetails
  # GET /orderdetails.json
  def index
    @orderdetails = Orderdetail.all
  end

  # GET /orderdetails/1
  # GET /orderdetails/1.json
  def show
  end

  # GET /orderdetails/new
  def new
    @orderdetail = Orderdetail.new
  end

  # GET /orderdetails/1/edit
  def edit
  end

  # POST /orderdetails
  # POST /orderdetails.json
  def create
    @orderdetail = Orderdetail.new(orderdetail_params)

    respond_to do |format|
      if @orderdetail.save
        format.html { redirect_to @orderdetail, notice: 'Orderdetail was successfully created.' }
        format.json { render :show, status: :created, location: @orderdetail }
      else
        format.html { render :new }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderdetails/1
  # PATCH/PUT /orderdetails/1.json
  def update
    respond_to do |format|
      if @orderdetail.update(orderdetail_params)
        format.html { redirect_to @orderdetail, notice: 'Orderdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderdetail }
      else
        format.html { render :edit }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderdetails/1
  # DELETE /orderdetails/1.json
  def destroy
    @orderdetail.destroy
    respond_to do |format|
      format.html { redirect_to orderdetails_url, notice: 'Orderdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderdetail
      @orderdetail = Orderdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderdetail_params
      params.require(:orderdetail).permit(:orderNumber, :productCode, :quantityOrdered, :priceEach, :orderLineNumber)
    end
end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/views/orderdetails/_form.html.erb
<%= form_with(model: orderdetail, local: true) do |form| %>
  <% if orderdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orderdetail.errors.count, "error") %> prohibited this orderdetail from being saved:</h2>

      <ul>
      <% orderdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :orderNumber %>
    <%= form.number_field :orderNumber, id: :orderdetail_orderNumber %>
  </div>

  <div class="field">
    <%= form.label :productCode %>
    <%= form.text_field :productCode, id: :orderdetail_productCode %>
  </div>

  <div class="field">
    <%= form.label :quantityOrdered %>
    <%= form.number_field :quantityOrdered, id: :orderdetail_quantityOrdered %>
  </div>

  <div class="field">
    <%= form.label :priceEach %>
    <%= form.text_field :priceEach, id: :orderdetail_priceEach %>
  </div>

  <div class="field">
    <%= form.label :orderLineNumber %>
    <%= form.number_field :orderLineNumber, id: :orderdetail_orderLineNumber %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orderdetails/edit.html.erb
<h1>Editing Orderdetail</h1>

<%= render 'form', orderdetail: @orderdetail %>

<%= link_to 'Show', @orderdetail %> |
<%= link_to 'Back', orderdetails_path %>

app/views/orderdetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orderdetails</h1>

<table>
  <thead>
    <tr>
      <th>Ordernumber</th>
      <th>Productcode</th>
      <th>Quantityordered</th>
      <th>Priceeach</th>
      <th>Orderlinenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orderdetails.each do |orderdetail| %>
      <tr>
        <td><%= orderdetail.orderNumber %></td>
        <td><%= orderdetail.productCode %></td>
        <td><%= orderdetail.quantityOrdered %></td>
        <td><%= orderdetail.priceEach %></td>
        <td><%= orderdetail.orderLineNumber %></td>
        <td><%= link_to 'Show', orderdetail %></td>
        <td><%= link_to 'Edit', edit_orderdetail_path(orderdetail) %></td>
        <td><%= link_to 'Destroy', orderdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orderdetail', new_orderdetail_path %>

app/views/orderdetails/new.html.erb
<h1>New Orderdetail</h1>

<%= render 'form', orderdetail: @orderdetail %>

<%= link_to 'Back', orderdetails_path %>

app/views/orderdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ordernumber:</strong>
  <%= @orderdetail.orderNumber %>
</p>

<p>
  <strong>Productcode:</strong>
  <%= @orderdetail.productCode %>
</p>

<p>
  <strong>Quantityordered:</strong>
  <%= @orderdetail.quantityOrdered %>
</p>

<p>
  <strong>Priceeach:</strong>
  <%= @orderdetail.priceEach %>
</p>

<p>
  <strong>Orderlinenumber:</strong>
  <%= @orderdetail.orderLineNumber %>
</p>

<%= link_to 'Edit', edit_orderdetail_path(@orderdetail) %> |
<%= link_to 'Back', orderdetails_path %>