config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :productlines
  resources :payments
  resources :orders
  resources :orderdetails
  resources :offices
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root to: 'products#index'
end

app/models/office.rb
class Office < ApplicationRecord
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:city, :phone, :addressLine1, :addressLine2, :state, :country, :postalCode, :territory)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_with(model: office, local: true) do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :office_city %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :office_phone %>
  </div>

  <div class="field">
    <%= form.label :addressLine1 %>
    <%= form.text_field :addressLine1, id: :office_addressLine1 %>
  </div>

  <div class="field">
    <%= form.label :addressLine2 %>
    <%= form.text_field :addressLine2, id: :office_addressLine2 %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :office_state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :office_country %>
  </div>

  <div class="field">
    <%= form.label :postalCode %>
    <%= form.text_field :postalCode, id: :office_postalCode %>
  </div>

  <div class="field">
    <%= form.label :territory %>
    <%= form.text_field :territory, id: :office_territory %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offices</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Phone</th>
      <th>Addressline1</th>
      <th>Addressline2</th>
      <th>State</th>
      <th>Country</th>
      <th>Postalcode</th>
      <th>Territory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.city %></td>
        <td><%= office.phone %></td>
        <td><%= office.addressLine1 %></td>
        <td><%= office.addressLine2 %></td>
        <td><%= office.state %></td>
        <td><%= office.country %></td>
        <td><%= office.postalCode %></td>
        <td><%= office.territory %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @office.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @office.phone %>
</p>

<p>
  <strong>Addressline1:</strong>
  <%= @office.addressLine1 %>
</p>

<p>
  <strong>Addressline2:</strong>
  <%= @office.addressLine2 %>
</p>

<p>
  <strong>State:</strong>
  <%= @office.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @office.country %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @office.postalCode %>
</p>

<p>
  <strong>Territory:</strong>
  <%= @office.territory %>
</p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>