config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :productlines
  resources :payments
  resources :orders
  resources :orderdetails
  resources :offices
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root to: 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  self.primary_key = "productCode"
  belongs_to :productlines, class_name: 'Productline', foreign_key: 'productLine'
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.limit 9
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:productName, :productLine, :productScale, :productVendor, :productDescription, :quantityInStock, :buyPrice, :MSRP)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :productName %>
    <%= form.text_field :productName, id: :product_productName %>
  </div>

  <div class="field">
    <%= form.label :productLine %>
    <%= form.text_field :productLine, id: :product_productLine %>
  </div>

  <div class="field">
    <%= form.label :productScale %>
    <%= form.text_field :productScale, id: :product_productScale %>
  </div>

  <div class="field">
    <%= form.label :productVendor %>
    <%= form.text_field :productVendor, id: :product_productVendor %>
  </div>

  <div class="field">
    <%= form.label :productDescription %>
    <%= form.text_area :productDescription, id: :product_productDescription %>
  </div>

  <div class="field">
    <%= form.label :quantityInStock %>
    <%= form.number_field :quantityInStock, id: :product_quantityInStock %>
  </div>

  <div class="field">
    <%= form.label :buyPrice %>
    <%= form.text_field :buyPrice, id: :product_buyPrice %>
  </div>

  <div class="field">
    <%= form.label :MSRP %>
    <%= form.text_field :MSRP, id: :product_MSRP %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<main id="product-container">
	<% @products.each do |product| %>
		<section class='product'>
			<%= link_to image_tag(product.productlines.image || 'missing.jpg' ), product_path(product) %>
			<h3><%= product.productName %></h3>
			<p><%= product.MSRP %></p>
			<section>
				<%= link_to product_path(product) do %>
				  <%= image_tag('details-icon.png' || 'missing.jpg' ) %>
				  <br>View
				<% end %>
				<%= link_to '#' do %>
				  <%= image_tag('add-icon.png' || 'missing.jpg') %>
				  <br>Add
				<% end %>
			</section>
		</section>
	<% end %>
</main>
	
<br>

<%= link_to 'New Product', new_product_path, class: 'btn' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div id="product-detail">
	<%= image_tag(@product.productlines.image || 'missing.jpg' ) %>
	
	<div>
		<h1><%= @product.productName %></h1>

		<h3><%= @product.buyPrice %></h3>

		<p><b>Vendor: </b><%= @product.productVendor %></p>

		<p><b>Description: </b><%= @product.productDescription %></p>
		
		<nav>
			<%= link_to 'Add to Cart', '#' %>
			<%= link_to 'Edit', edit_product_path(@product) %>
			<%= link_to 'Back', products_path %>
		</nav>
	</div>
</div>